spring.application.name=srping-rest
spring.datasource.url=jdbc:postgresql://localhost:5432/school_db
spring.datasource.username=postgres
spring.datasource.password=Avocado*2002



logging.level.root=warn

spring.main.banner-mode=off

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

spring.jpa.hibernate.ddl-auto=update